### ISSUE TITLE
Published Status: REJECTED_UNKNOWN

### ISSUE THREAD

**Issue by AkipTsaqif** [jarrah31/Google-StreetView-Publish-WebGUI#1]
I've successfully setup this app and tried to upload my first equirectangular photosphere. It successfully uploads but the published status is rejected. Is this rejected by Google? If yes why would it gets rejected?

**Comment by jarrah31** [comment]
Hi @AkipTsaqif, thank you for giving this a go and sorry to hear about the rejected error. I must have uploaded 50+ photos now and never once had one rejected so I'm not sure what could cause this. Do you have any other 360 photos on your Google account that are viewable via the View Photos page? After selecting an image on the Upload page, do all attributes turn green to indicate they are valid? (this checks for valid metadata in the photo that Google requires)

**Comment by AkipTsaqif** [comment]
It do turns green for all of the attributes. Also I could see the photosphere is successfully uploaded on my contribution page. It has the correct thumbnail, but whenever I try to view it, its blank (black screen). Not sure if this is caused by the REJECTED_UNKNOWN status there.

Also also, is the file name supposed to be in json format and not the jpg format from the view photos page? Is this the culprit?

**Comment by jarrah31** [comment]
> is the file name supposed to be in json format and not the jpg format from the view photos page

Ah yes I can see how this is confusing. The json filename refers to a file stored in the "uploads" folder in the same directory where app.py is. This file contains useful photo details such as the photoID and web links to the image.

Unfortunately Google gives no useful reason behind there rejected error as seen here:
https://developers.google.com/streetview/publish/reference/rpc/google.streetview.publish.v1#mapspublishstatus

This page gives a little more information:
https://www.google.com/streetview/policy/trusted/#:~:text=Individual%20responsibility,Google%20Maps%20Terms%20of%20Service.

> While published images are typically visible on Google Maps within seconds, these images may subsequently be rejected if they are not in compliance with [Maps User Contributed Content Policy](https://support.google.com/contributionpolicy/answer/7422880?hl=%(locale)s) or the [Google Maps Terms of Service](https://cloud.google.com/maps-platform/terms/).

Do you have another photo that you could try? It seems the uploading process is working fine, it's just Google's automated reviews rejected it for some reason. :(

**Comment by AkipTsaqif** [comment]
I just realized that if I open the photosphere from my phone, it shows normally and the maps directional arrow is exactly on where it is taken even though there aren't any blue dot there (can move to nearby photosphere by someone else and can't go back to mine). I can't see this photosphere from anywhere else except from my phone.

Let me try to upload something else and on a different place to see if it would get rejected again.

**Comment by jarrah31** [comment]
I've been looking back through my 360 photos going back years and seen that some of those have now been rejected, even when there's been over 20,000 views. Shame there's no way to find out why photos have been rejected...
